### ISSUE TITLE
limited shell

### ISSUE THREAD

**Issue by kermit832** [mumoshu/kube-ssm-agent#4]
Hi Mumoshu,

The daemonset works pretty well to connect to the server but seems like its a limited bash experiences. 

For example, ssm with daemonset:
```
sh-4.2$ ps
sh: ps: command not found
```
ssm installed via user data
```
root@ip-x-x-x-x bin]# ps
  PID TTY          TIME CMD
20954 pts/0    00:00:00 sudo
20960 pts/0    00:00:00 su
20962 pts/0    00:00:00 bash
20989 pts/0    00:00:00 ps
[root@ip-10-107-18-210 bin]# ps -aux
```
I'm currently testing node groups so I have both managed and manually deployed eks nodes with ssm installed via userdata.

Let me know if you have an idea of what the issue could be. Thanks

**Comment by kermit832** [comment]
I actually found another ssm daemonset deployment that you seem to have some involvement in  and from trying a few images in his repo, an old image seems to give full ssm controls. 

```
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      containers:
      **- image: alexeiled/aws-ssm-agent:2.3.680**
        imagePullPolicy: Always
        name: ssm-agent
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
```

The other images didn't work, kept getting stuck in a crashback loop but this seems to be in working order. 

if anyone else is running into this, heres the other repo in question. Pretty much its the same deployment, I just referenced an older image. https://github.com/alexei-led/kube-ssm-agent

Thanks
